version: 2
env:
  - GO111MODULE=on

# before:
#   hooks:
#     - ./scripts/manpages.sh
#     - ./scripts/completions.sh

builds:
  - id: seulogin
    main: .
    binary: seulogin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.buildTime={{ .Date }}
      - -X main.gitCommit={{ .FullCommit }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm64
      - arm
      - mips64
      - mips64le
      - mipsle
      - riscv64
    goarm:
      - "7"
    overrides:
      - goos: darwin
        goarch: amd64
        ldflags:
          - -s -w
        env:
          - CGO_ENABLED=0
      - goos: darwin
        goarch: arm64
        ldflags:
          - -s -w
        env:
          - CGO_ENABLED=0
      - goos: linux
        ldflags:
          - -s -w -extldflags "-static"
          - -X main.version={{ .Version }}
          - -X main.buildTime={{ .Date }}
          - -X main.gitCommit={{ .FullCommit }}


archives:
  -
    builds:
      - seulogin
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - builds:
      - seulogin
    vendor: SmartFPGATutor
    homepage:  https://github.com/SmartFPGATutor/seulogin
    maintainer: "dengqqi <dengqqi935@gmail.com>"
    description: "A command line tool to login to Southeast University Network"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux
      - termux.deb
    bindir: /usr/bin
    contents:
      - src: ./scripts/systemctl/seulogin@.service
        dst: /lib/systemd/system/seulogin@.service
        type: config
        packager: deb
      - src: ./scripts/systemctl/seulogin@.service
        dst: /lib/systemd/system/seulogin@.service
        type: config
        packager: archlinux
      - src: ./scripts/systemctl/seulogin@.service
        dst: /usr/lib/systemd/system/seulogin@.service
        type: config
        packager: rpm
      - src: ./scripts/rc/seulogin
        dst: /etc/init.d/seulogin
        type: config
        packager: apk
    #   - src: ./manpages/seulogin.1.gz
    #     dst: /usr/share/man/man1/seulogin.1.gz
    #     file_info:
    #       mode: 0644
    #   - src: ./completions/seulogin.bash
    #     dst: /usr/share/bash-completion/completions/seulogin
    #     file_info:
    #       mode: 0644
    #   - src: ./completions/seulogin.fish
    #     dst: /usr/share/fish/vendor_completions.d/seulogin.fish
    #     file_info:
    #       mode: 0644
    #   - src: ./completions/seulogin.zsh
    #     dst:  /usr/share/zsh/vendor-completions/_seulogin
    #     file_info:
    #       mode: 0644
    scripts:
      postinstall: ./scripts/post-install.sh
      postremove: ./scripts/post-remove.sh

release:
  github:
    owner: SmartFPGATutor
    name: seulogin

# dockers:
# - image_templates:
#   - 'nerdneils/{{.ProjectName}}:{{ .Tag }}-amd64'
#   - 'ghcr.io/SmartFPGATutor/{{.ProjectName}}:{{ .Tag }}-amd64'
#   dockerfile: Dockerfile
#   use: buildx
#   build_flag_templates:
#   - "--pull"
#   - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/SmartFPGATutor/seulogin/master/README.md"
#   - "--label=io.artifacthub.package.maintainers=[{\"name\":\"dengqqi\",\"email\":\"dengqqi935@gmail.com\"}]"
#   - "--label=io.artifacthub.package.license=MIT"
#   - "--label=org.opencontainers.image.description=A command line tool to login to Southeast University Network"
#   - "--label=org.opencontainers.image.created={{.Date}}"
#   - "--label=org.opencontainers.image.name={{.ProjectName}}"
#   - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#   - "--label=org.opencontainers.image.version={{.Version}}"
#   - "--label=org.opencontainers.image.source={{.GitURL}}"
#   - "--platform=linux/amd64"
#   extra_files:
#     - config_example.toml
# - image_templates:
#   - 'nerdneils/{{.ProjectName}}:{{ .Tag }}-arm64'
#   - 'ghcr.io/SmartFPGATutor/{{.ProjectName}}:{{ .Tag }}-arm64'
#   dockerfile:  Dockerfile
#   use: buildx
#   build_flag_templates:
#   - "--pull"
#   - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/SmartFPGATutor/seulogin/master/README.md"
#   - "--label=io.artifacthub.package.logo-url=https://raw.githubusercontent.com/SmartFPGATutor/seulogin/master/www/static/images/logo.png"
#   - "--label=io.artifacthub.package.maintainers=[{\"name\":\"dengqqi\",\"email\":\"dengqqi935@gmail.com\"}]"
#   - "--label=io.artifacthub.package.license=MIT"
#   - "--label=org.opencontainers.image.description=A command line tool to login to Southeast University Network"
#   - "--label=org.opencontainers.image.created={{.Date}}"
#   - "--label=org.opencontainers.image.name={{.ProjectName}}"
#   - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#   - "--label=org.opencontainers.image.version={{.Version}}"
#   - "--label=org.opencontainers.image.source={{.GitURL}}"
#   - "--platform=linux/arm64"
#   goarch: arm64
#   extra_files:
#     - config_example.toml
#
# docker_manifests:
# - name_template: 'nerdneils/{{.ProjectName}}:{{ .Tag }}'
#   image_templates:
#   - 'nerdneils/{{.ProjectName}}:{{ .Tag }}-amd64'
#   - 'nerdneils/{{.ProjectName}}:{{ .Tag }}-arm64'
# - name_template: 'ghcr.io/SmartFPGATutor/{{.ProjectName}}:{{ .Tag }}'
#   image_templates:
#   - 'ghcr.io/SmartFPGATutor/{{.ProjectName}}:{{ .Tag }}-amd64'
#   - 'ghcr.io/SmartFPGATutor/{{.ProjectName}}:{{ .Tag }}-arm64'
# - name_template: 'nerdneils/{{.ProjectName}}:latest'
#   image_templates:
#   - 'nerdneils/{{.ProjectName}}:{{ .Tag }}-amd64'
#   - 'nerdneils/{{.ProjectName}}:{{ .Tag }}-arm64'
# - name_template: 'ghcr.io/SmartFPGATutor/{{.ProjectName}}:latest'
#   image_templates:
#   - 'ghcr.io/SmartFPGATutor/{{.ProjectName}}:{{ .Tag }}-amd64'
#   - 'ghcr.io/SmartFPGATutor/{{.ProjectName}}:{{ .Tag }}-arm64'

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
